### ISSUE TITLE
Consider adding native flake support?

### ISSUE THREAD

**Issue by otavio** [katyo/zephyr-rtos.nix#3]
I use this with a flake, it'd be nice to have it supported. Are you willing to accept a PR for it?

**Comment by katyo** [comment]
@otavio Any contributions are welcome!

**Comment by otavio** [comment]
I added #4 to fix this issue. Should we continue supporting `nix-shell` or switch to `flake` exclusively?

**Comment by katyo** [comment]
@otavio I would like continue support nix-shell.

**Comment by otavio** [comment]
I personally prefer using flakes over nix-shell. However, there is no cause for concern.
