### ISSUE TITLE
Use Nix to setup the Python environment of SDK 

### ISSUE THREAD

**Issue by otavio** [katyo/zephyr-rtos.nix#5]
In an internal project, we use Nix for the development environment but until now we still use Docker for the SDK inside the CI. We'd like to use the same environment on CI but due to how the `venv` activation works, it fails.

Is it possible to get the  Python environment of SDK in Nix?

**Comment by katyo** [comment]
@otavio Good idea but note that some python dependencies still lacks in NixOS repo.
In any case we should instantiate environment from `requirements.txt` which contained in Zephyr. Currently I don't know an easy nix-based way to do it.

**Comment by otavio** [comment]
I know two options:

- https://github.com/nix-community/dream2nix/
- https://github.com/DavHau/mach-nix

**Comment by otavio** [comment]
Did you evaluate any of those options?

**Comment by otavio** [comment]
Fixed in #8
